[25기 성해호] FIX : slick 기능 구현중
wecode-bootcamp-korea/25-2nd-NoSleepPlace-frontend pull request #3
Opened 2021-10-19 08:29 UTC by heyho00

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [x] 리뷰 반영
- [x] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- 메인 레이아웃 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
- 메인페이지 레이아웃 구현 완료
- Slick 이용해 slide 기능 구현 중.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- 레이아웃 완성 후, 카테고리, 슬라이드, Vertical AD 등에서 백엔드 통신 예정.
- slick 라이브러리 활용해 슬라이드바 만들어보며 라이브러리 사용법, 스타일 주는법을 알게됨.
- slick 기본 css가 적용되어있어  개발자 도구 활용해 요소들을 찾아 스타일링함.

![스크린샷 2021-10-20 19 51 13](https://user-images.githubusercontent.com/75261551/138079944-e2ea492a-7f68-4850-b2dd-ce6aec3c6b33.png)
- map함수 배개변수 안에서 props를 이름 지정하지 않고 바로 구조분해할당 하는법을 알게됨.

![스크린샷 2021-10-20 19 52 34](https://user-images.githubusercontent.com/75261551/138080135-dd1bb5b9-abf7-4578-8ed3-4810d5da1368.png)
- 상수데이터 삽입시 맨 뒤로 위치시켜 컴포넌트가 앞으로 나오는게 가독성이 좋다. 항상 가독성에 신경써야겠다.
- 상수임을 명확히 표현하기 위해서 UPPERCASE + snake_case 로 구성하는게 좋다. (ex. IMAGE_LIST)

<br />

## :: 기타 질문 및 특이 사항
- 카테고리 목데이터 활용, 동적라우팅 적용할 예정.
- 위아래로 움직이는 Slide 기능은 연구중.

2021-10-20 07:40 UTC, younuk23 commented on src/Routes.js
> +        <div style={{ marginTop: '100px' }} />
inline style 지양해주세요

2021-10-20 07:41 UTC, younuk23 commented on src/pages/Main/Banner.js
> +`;
이렇게 네스팅 depth를 깊게 하시는 것 보다 각 스타일 부여하는 부분을 스타일드 컴포넌트로 선언해서 스타일 주는 방식으로 활용해주세요! 간단한 1depth의 네스팅 정도는 큰 문제 없겠지만 이렇게 네스팅 depth를 점점 깊게 가져가면은 쓸때는 편해도 나중에 유지보수하기 힘들어집니다

2021-10-20 07:41 UTC, younuk23 commented on src/pages/Main/Category.js
> +  render() {
다른 메소드끼리는 한줄 공백 부여하는게 가독성상 좋습니다

2021-10-20 07:41 UTC, younuk23 commented on src/pages/Main/Category.js
> +    return (
return문 위도 변수 선언과 return은 다른 문맥이니까 한줄 공백 주는게 좋습니다! 가독성상!

2021-10-20 07:42 UTC, younuk23 commented on src/pages/Main/Category.js
> +        {categories.map((el, index) => {
el이라는 이름은 이제 인생에 없습니다! 매개변수명에서 의미가 잘 드러나도록 이름 지어주세요!, 그리고 el부분 매개변수 자리에서 바로 구조분해 해버려도 좋겠네요

2021-10-20 07:43 UTC, younuk23 commented on src/pages/Main/Main.js
> +            <button type="button" onclick="location.href='/'">
onclick 부분 그냥 html에서 쓰듯이 쓴 것 같은데요? 레퍼런스 보고 참고하는 건 좋지만 이해없이 그대로 긁어와서 쓰는건 안좋습니다 수정해주세요

2021-10-20 07:44 UTC, younuk23 commented on src/pages/Main/Suggest.js
> +const ImageLists = [
이런 상수데이터 같은경우에는 데이터 길이가 길어서 파일 최하단에 넣는게 좋습니다
개발자가 Suggest.js 파일에 들어왔을 때 보고싶은건 컴포넌트지 상수데이터가 아니니까요!
그리고 상수데이터는 상수임을 명확히 표현하기 위해서 UPPERCASE + snake_case 로 구성하는게 좋습니다!
IMAGE_LIST

2021-10-20 07:47 UTC, younuk23 requested changes
리뷰 확인 및 반영해주세요!

2021-10-21 01:10 UTC, younuk23 commented on src/pages/Main/Category.js
> +  render() {
👍

2021-10-21 01:12 UTC, younuk23 commented on src/pages/Main/Main.js
> +  width: 100%;
불필요한 코드입니다 왜 불필요한지 코멘트로 설명해주세요

2021-10-21 01:14 UTC, younuk23 commented on src/pages/Main/Suggest.js
> +              <img key={images.id} alt="places" src={images.src} />
key props 는 최상위 태그에 부여되어야합니다 근데 이 코드에서는 최상위 태그는 img도 PlaceInfo도 아닌 Fragment같네요! Fragment에 key prop 부여할 수 있으니까 한번 찾아서 적용해보세요, 

그리고 아마 key props 제대로 부여안됬다고 console에 워닝 출력되고 있을겁니다! 항상 콘솔창도 잘 확인해주세요

2021-10-21 01:14 UTC, younuk23 commented on src/pages/Main/Suggest.js
> +  border-bottom: 1px solid #e1e5e4;
이렇게 자주 쓰이는 색상들 theme에 변수로 담아두고 사용하면 유지보수에 좋겠네요! 팀원들이랑 같이 상의해서 적용해보세요ㄹ

2021-10-21 05:48 UTC, heyho-time commented
> 리뷰 확인 및 반영해주세요! 코멘트에 반영했다고 응답주는것 👍 , 캡쳐해서 보여주시는것도 👍 다만, 캡쳐하는데 시간 너무 오래걸리면 캡쳐까지는 필요는 없습니다.
> 
> 그리고 PR 본문에 양식 깨진 것 있으니까 확인해주세요! 리뷰요청전에 PR 본문이랑 라벨, File Changed 한번 확인하는 습관 들이는게 좋습니다!

PR 본문 확인했습니다. 
본문, 라벨, File changed 확인 습관 들이겠습니다 !

2021-10-21 06:38 UTC, heyho-time commented on src/pages/Main/Suggest.js
> +  border-bottom: 1px solid #e1e5e4;
아하, 알겠습니다 !

2021-10-25 04:33 UTC, merged